### ISSUE TITLE
1.18.1: LinkedHashMap is not serialized properly when saving settings.yml with comments

### ISSUE THREAD

**Issue by matobodo** [kangarko/Foundation#138]
https://github.com/kangarko/Foundation/blob/497045f17e4467e608b883abc15a1d4d33c98505/src/main/java/org/mineacademy/fo/settings/YamlComments.java#L277-L306

When `List<LinkedHashMap>` is passed to `getListAsString()` method, the LinkedHashMap is serialized using `toString()` method, which produces invalid yaml syntax. 
```yaml
MobChances:
  - {Name=ZOMBIE, Chance=0.4}
  - {Name=SKELETON, Chance=0.4}
  - {Name=CREEPER, Chance=0.2}
```
Instead, Maps should be treated separately and serialized as follows.
```yaml
MobChances:
  - Name: ZOMBIE
    Chance: 0.4
  - Name: SKELETON
    Chance: 0.4
  - Name: CREEPER
    Chance: 0.2
```
