### ISSUE TITLE
1.20.4: SimpleSettings saves multi-line strings incorrectly

### ISSUE THREAD

**Issue by Kanin** [kangarko/Foundation#278]
[Here's the YAML docs on block strings](https://yaml.org/spec/1.2.2/#chapter-8-block-style-productions)

# Steps to reproduce
1. Add a multi-line string to your settings file, e.g:
```yml
Scythes:
  - name: "&fBasic Scythe"
    lore: |-
      &7A basic scythe
      
      &f&lCOMMON
    tier: 1
    material: "WOODEN_HOE"
    glowing: true
```
2. Start your server
3. Check your settings.yml file
4. Notice the multi-line string has been changed to:
```yml
Scythes:
  - name: "&fBasic Scythe"
    lore: |-
    &7A basic scythe
    
    &f&lCOMMON
    tier: 1
    material: "WOODEN_HOE"
    glowing: true
```
5. Attempt to restart your server and see that the plugin can no longer load settings.yml because it saved this to an un-parseable state.

# SimpleSettings class & settings.yml
[Relevant Files](https://gist.github.com/Kanin/6bb19058569a81d1825905b30294c70e)
